version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - echo "Installing SAM CLI"
      - pip install aws-sam-cli
      - echo "SAM CLI installed"
      - echo "Current directory:" && pwd
      - ls -al
      - sam build -t devops/template.yml
      - echo "Pipeline bucket name $PIPELINE_BUCKET"
      - sam package --s3-bucket $PIPELINE_BUCKET --output-template-file packaged.yaml

artifacts:
  files:
    - packaged.yaml



