version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - pip install aws-sam-cli
      - sam build
      - sam package \
          --s3-bucket $PIPELINE_BUCKET \
          --output-template-file packaged.yaml
      - sam deploy \
          --template-file packaged.yaml \
          --stack-name auth-sam-api \
          --capabilities CAPABILITY_IAM
artifacts:
  files:
    - packaged.yaml

