version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - echo "Installing sam cli"
      - pip install aws-sam-cli
      - echo "Sam cli installed"
      - echo "Current dir:" && pwd
      - ls -al
      - sam build -t devops/template.yml
      - sam package \
          --s3-bucket $PIPELINE_BUCKET \
          --output-template-file packaged.yaml
      - sam deploy \
          --template-file packaged.yaml \
          --stack-name test-auth-sam-api \
          --capabilities CAPABILITY_IAM
artifacts:
  files:
    - packaged.yaml


