AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Auth API with Signup and Login using AWS SAM

Globals:
  Function:
    Runtime: python3.9
    Timeout: 10
    MemorySize: 128

Resources:

  SignupFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: signup-handler
      Handler: signup.lambda_handler
      CodeUri: src/
      Events:
        SignupAPI:
          Type: Api
          Properties:
            Path: /signup
            Method: post

  LoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: login-handler
      Handler: login.lambda_handler
      CodeUri: src/
      Events:
        LoginAPI:
          Type: Api
          Properties:
            Path: /login
            Method: post
